server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.3.10:3306/permissions_framework?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    MapUnderscoreToCamelCase: true
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 192.168.3.10
    port: 6379
    database: 8
  thymeleaf:
    cache:  false
    mode: LEGACYHTML5
com:
  daqsoft:
    captcha:
      random-code: 1234567890QWERTYUPASDFGHJKZXCVBNM
      code-count: 4
      world-space: 30
      font-size: 40
      height: 55
      back-ground-color:
        a: 0
        b: 120
        g: 120
        r: 120
      #code-unicode-scope: 30000-40000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/*Mapper.xml
